In [35]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [33]:
# lets start with the series
obj = pd.Series([-4,3,4,7,8])
obj

0   -4
1    3
2    4
3    7
4    8
dtype: int64

In [34]:
obj.value_counts()

-4    1
 3    1
 4    1
 7    1
 8    1
dtype: int64

In [33]:
# using index and values attributes
obj.values

array([-4,  3,  4,  7,  8], dtype=int64)

In [34]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [39]:
obj.value_counts()

-4    1
 3    1
 4    1
 7    1
 8    1
dtype: int64

In [41]:
obj2 = pd.Series([-5,6-7,8,9], index=['d', 'b', "a", "c"])
obj2

d   -5
b   -1
a    8
c    9
dtype: int64

In [42]:
obj2.values

array([-5, -1,  8,  9], dtype=int64)

In [43]:
obj2. index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [44]:
obj2['a']

8

In [45]:
obj2[["a", "c", "b"]]

a    8
c    9
b   -1
dtype: int64

In [46]:
obj2['a']=2
obj2

d   -5
b   -1
a    2
c    9
dtype: int64

In [49]:
obj2

d   -5
b   -1
a    2
c    9
dtype: int64

In [50]:
obj2[obj2>0]

a    2
c    9
dtype: int64

In [51]:
np.exp(obj2)

d       0.006738
b       0.367879
a       7.389056
c    8103.083928
dtype: float64

In [52]:
# performing boolean functions
"b" in obj2

True

In [53]:
('b' not in obj)

True

In [55]:
#Should you have data contained in a Python dict, you can create a Series from it by passing the dict
sdata = {"Ohio":35000, "Texas":71000, "Oregon": 16000, "Utah":5000}
obj = pd.Series(sdata)
obj

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [56]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj = pd.Series(sdata, index = states)
obj

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [57]:
pd.isnull(obj)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [58]:
pd.notnull(obj)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [59]:
obj.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [60]:
obj.name = 'Population'
obj.index.name = "states"
obj

states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

In [3]:
## Lets construct the data frames
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [4]:
data['pop']

[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]

In [5]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [6]:
# we can also speicy the sequence of columns
frame = pd.DataFrame(data, columns=['state', 'pop', 'year'])
frame

state  pop  year
0    Ohio  1.5  2000
1    Ohio  1.7  2001
2    Ohio  3.6  2002
3  Nevada  2.4  2001
4  Nevada  2.9  2002
5  Nevada  3.2  2003

In [7]:
# passing a column which is not in the dataframe
frame = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                    index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [46]:
frame.pop

<bound method DataFrame.pop of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN>

In [10]:
## we can also retrieve the rows by using loc
frame.iloc[5]

year       2003
state    Nevada
pop         3.2
debt        NaN
Name: six, dtype: object

In [13]:
## assigning columns specific values
frame['debt'][-1]= 16
frame

C:\Users\muhammad.adil\AppData\Local\Temp\ipykernel_17948\1598837451.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['debt'][-1]= 16


year   state  pop  debt
one    2000    Ohio  1.5    16
two    2001    Ohio  1.7    16
three  2002    Ohio  3.6    16
four   2001  Nevada  2.4    16
five   2002  Nevada  2.9    16
six    2003  Nevada  3.2    16

In [59]:
# or using np.arange to assign the values
frame.debt = np.arange(6.)
frame

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [14]:
# assigning a series to a data frame, its labels will be realigned exactly to the index of data frame
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [15]:
frame.debt = val
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [16]:
## assigning a column that does not exist will create a new column, which we can delete using del keyword
## new column cannot be created using frame.eastern syntax
frame['eastern']=frame.state=='Ohio'
frame

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [17]:
del frame['eastern']
frame

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [18]:
frame.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [19]:
## another form of dataframe is nested dict of dicts
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
      'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop = pd.DataFrame(pop)
pop

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [20]:
## we can take a transpose to the dataframe similarly as numpy
pop.transpose()

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [21]:
## the keys above in the inner dicts are combined to form the index,
## this is not True if an explicit index is specified
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [31]:
pop.Ohio[:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [32]:
# we can also specify the name of the index and columns
pop.index.name = 'year'
pop.columns.name = 'states'
pop

states  Nevada  Ohio
year                
2001       2.4   1.7
2002       2.9   3.6
2000       NaN   1.5

In [35]:

pop.value_counts

<bound method DataFrame.value_counts of states  Nevada  Ohio
year                
2001       2.4   1.7
2002       2.9   3.6
2000       NaN   1.5>

In [78]:
frame.value_counts

<bound method DataFrame.value_counts of        year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN>

In [37]:
# index objects
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj.index[1], obj # index are immutable, thus cannot be modified

('b',
 a    0
 b    1
 c    2
 dtype: int64)

In [38]:
labels = pd.Index(np.arange(3), dtype='int32')
labels

Int64Index([0, 1, 2], dtype='int64')

In [39]:
obj2 = pd.Series([1.5, -2.5,0], index=labels)
obj2.index is labels

True

In [40]:
obj.index is labels

False

In [41]:
pop.columns

Index(['Nevada', 'Ohio'], dtype='object', name='states')

In [42]:
'Ohio' in pop.columns

True

In [43]:
# pandas index can contain duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels
df= pd.DataFrame(np.arange(4), index=dup_labels)

In [44]:
df[0:]

0
foo  0
foo  1
bar  2
bar  3

In [45]:
## reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [46]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [47]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [48]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [49]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [50]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [52]:
states = ['Texas', 'Utah', 'California']
frame3 = frame2.reindex(columns=states)
frame3

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [55]:
frame3.loc['a']

Texas         1.0
Utah          NaN
California    2.0
Name: a, dtype: float64

In [56]:
## droping entries from an axis
obj = pd.Series(np.arange(5.,), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [60]:
new_obj = obj.drop(["c"])
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [8]:
## droping multiple indexes
new_obj = obj.drop(['a','b'])
new_obj

c    2.0
d    3.0
e    4.0
dtype: float64

In [61]:
## droping an index from a dataframe
data = pd.DataFrame(np.arange(16).reshape(4,4), index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [64]:
data.drop(['Utah'])

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [65]:
## droping values from axis=1 -> columns
data.drop(['four'], axis=1)

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [69]:
## we can use inplace=True to save the drop state
data.drop(['Colorado'], inplace=True)
data

In [70]:
data

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(['Ohio'], inplace=True)

In [72]:
data

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [73]:
data.drop(['Utah'])

one  two  three  four
New York   12   13     14    15

In [74]:
## indexing, filtering and selection
## series indexing works exactly like numpy array with only difference we can use series index values instead of only integer values
obj = pd.Series(np.arange(4.,), index = ['a', 'b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [75]:
## selecting individual values
obj['d']

3.0

In [80]:
obj[1:-1]

b    1.0
c    2.0
dtype: float64

In [81]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [83]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [84]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [85]:
obj[obj>0]

b    1.0
c    2.0
d    3.0
dtype: float64

In [86]:
obj['b':'d'] ## here the end point is included if we slice it by using labels or index

b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj['b':'c'] = 4
obj

a    0.0
b    4.0
c    4.0
d    3.0
dtype: float64

In [88]:
## lets slice on dataFrames
data = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four']
                   )
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [91]:
data[1:2]

one  two  three  four
Colorado    4    5      6     7

In [93]:
data[data.three>3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [96]:
# using condition
data[data['three']>6]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data[data>5]

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   NaN    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [98]:
## assigning values 
data[data>5] = 5

In [99]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      5     5
Utah        5    5      5     5
New York    5    5      5     5

In [102]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
## selecting with loc-(axis label) and iloc-(integer label)
## this is specifically used for row indexing
## They enable us to select a subset of rows and columns from a dataframe


In [104]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
# lets select a single row
data.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [96]:
# now selecting the columns
data.loc['Colorado', ['three', 'one']]

three    6
one      4
Name: Colorado, dtype: int32

In [97]:
## similarly for other rows
data.loc['Ohio', ['one', 'four']]

one     0
four    3
Name: Ohio, dtype: int32

In [98]:
data.loc['Utah',['one','four']]

one      8
four    11
Name: Utah, dtype: int32

In [99]:
## now selecting using iloc
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data.iloc[0,[0,3]]

one     0
four    3
Name: Ohio, dtype: int32

In [101]:
data.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [102]:
data.iloc[2,[0,2,3]]

one       8
three    10
four     11
Name: Utah, dtype: int32

In [103]:
## Selecting multiple rows and multiples columns
data.loc[['Colorado','Utah'],['one','three']]

one  three
Colorado    4      6
Utah        8     10

In [104]:
## similarly with iloc
data.iloc[[0,1],[3,1]]

four  two
Ohio         3    1
Colorado     7    5

In [105]:
data.loc[:'Utah',['two','four']]

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11

In [135]:
data.iloc[:,:3][data.one>5]

one  two  three
Utah        8    9     10
New York   12   13     14

In [112]:
## integer indexes
ser = pd.Series(np.arange(4.), index=["a","b","c","d"])
ser

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [114]:
ser[1]

1.0

In [160]:
ser.iloc[:4]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [7]:
## arithmetic operations between different indexes
## on series
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])
print(s1, '\n\n', s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64 

 a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [8]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [9]:
# as we can see, values that are not overlapping, adding them results in NaN values
## in case of dataframe, alignment is performed on both the rows and the columns
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [10]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [11]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [12]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [14]:
## adding dataframe with zero overlapping values
df1 = pd.DataFrame({"A":[1,2]})
df2 = pd.DataFrame({"B":[3,4]})
df1

A
0  1
1  2

In [15]:
df2

B
0  3
1  4

In [16]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [17]:
## arithmetic methods with fill values
# with different index or with non-overlapping values, we can fill them with specific values
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [18]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [31]:
df1.loc[1, 'b']

5.0

In [33]:
df2.loc[1,'b'] = np.nan

In [34]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [35]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [37]:
# now we can add the specific values where valus dont overlap
df1.add(df2, fill_value= 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [38]:
df1.reindex(columns=df2.columns, fill_value=7)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  7
1  4.0  5.0   6.0   7.0  7
2  8.0  9.0  10.0  11.0  7

In [39]:
## operations between dataframe and series
# consider an example
arr = np.arange(12.0).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [48]:
arr[0:2, 1:3,]

array([[1., 2.],
       [5., 6.]])

In [49]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [38]:
# now lets look operations between dataframe and series
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [5]:
series = frame.loc['Utah']
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [6]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [7]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [8]:
series = pd.Series(range(3), index = list('bef'))
series


b    0
e    1
f    2
dtype: int64

In [10]:
frame - series

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [15]:
series

b    0
e    1
f    2
dtype: int64

In [18]:
frame.sub(series).fillna(0)

b    d     e    f
Utah    0.0  0.0   1.0  0.0
Ohio    3.0  0.0   4.0  0.0
Texas   6.0  0.0   7.0  0.0
Oregon  9.0  0.0  10.0  0.0

In [19]:
frame + series

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [21]:
frame.add(series).fillna(0)

b    d     e    f
Utah    0.0  0.0   3.0  0.0
Ohio    3.0  0.0   6.0  0.0
Texas   6.0  0.0   9.0  0.0
Oregon  9.0  0.0  12.0  0.0

In [22]:
## by default as we see that broadcasting happens between rows, if we want to broadcast between columns, then:
series = frame['d']
series

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [23]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [24]:
frame.sub(series, axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [25]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [26]:
# apply a lambda function
np.abs(frame)

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [35]:
frame.apply(lambda x: x.max() - x.min(), axis=1) # it is working column wise by default

Utah      2
Ohio      2
Texas     2
Oregon    2
dtype: int32

In [36]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame


b         d         e
Utah   -0.812684  1.312430  0.796192
Ohio    0.228617  0.080779 -1.108381
Texas  -0.787063 -1.017225 -0.326278
Oregon  0.781468  0.836986  0.295151

In [37]:
frame.apply(lambda x: x.max() - x.min())

b    1.594152
d    2.329654
e    1.904573
dtype: float64

In [41]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [42]:
frame.apply(f)

b   d   e
min  0   1   2
max  9  10  11

In [43]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [54]:
frame.applymap(lambda x: '%.2f' %x)

b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [55]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [60]:
frame.apply(lambda x: x.sort_values(ascending=False), axis=1)

e   d  b
Utah     2   1  0
Ohio     5   4  3
Texas    8   7  6
Oregon  11  10  9

In [67]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [68]:
frame.sort_values(by=['b'])

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [71]:
#Axis Indexes with Duplicate Labels
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [73]:
obj.index.is_unique

False

In [75]:
obj.a, obj.c

(a    0
 a    1
 dtype: int64,
 4)

In [81]:
df = pd.DataFrame(np.random.randn(5,3), columns=list('bde'), index=['a', 'a', 'b', 'b', 'c'])
df

b         d         e
a  0.174401  1.123007  0.582199
a -2.343894 -1.175670 -1.260866
b -0.586898 -0.890860  0.122638
b  0.002156  0.947071 -2.067822
c  0.958584 -0.803196  0.618894

In [84]:
df.loc['a'], df.loc['b']

(          b         d         e
 a  0.174401  1.123007  0.582199
 a -2.343894 -1.175670 -1.260866,
           b         d         e
 b -0.586898 -0.890860  0.122638
 b  0.002156  0.947071 -2.067822)

In [15]:
# Unique Values, Value Counts, and Membership
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
(obj.unique()), obj.value_counts()

(array(['c', 'a', 'd', 'b'], dtype=object),
 c    3
 a    3
 b    2
 d    1
 dtype: int64)

In [28]:
# The Series is sorted by value in descending order as a convenience. value_counts is
# also available as a top-level pandas method that can be used with any array or
# sequence:
pd.value_counts(obj.values, sort=True)

c    3
a    3
b    2
d    1
dtype: int64

In [31]:
# isin performs a vectorized set membership check and can be useful in filtering a
# dataset down to a subset of values in a Series or column in a DataFrame:
mask = obj.isin(['a','b'])
mask

0    False
1     True
2    False
3     True
4     True
5     True
6     True
7    False
8    False
dtype: bool

In [32]:
obj[mask]

1    a
3    a
4    a
5    b
6    b
dtype: object

In [33]:
# In some cases, you may want to compute a histogram on multiple related columns in
# a DataFrame. Here’s an example:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [34]:
results = data.apply(pd.value_counts).fillna(0)
results

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [37]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [38]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [41]:
df.cumsum(axis=1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55